/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Newsstand Management System API
 * Newsstand Management System RESTful API Documentation
 * OpenAPI spec version: v1.0.0
 */
/**
 * Resource conflict response
 */
export interface ConflictExceptionResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 响应数据 */
  data?: unknown;
  /** 数据总数量 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * Parameter validation failure response
 */
export interface ValidationExceptionResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 字段错误信息，格式：field1: message1; field2: message2 */
  errorMsg?: string;
  /** 响应数据 */
  data?: unknown;
  /** 数据总数量 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * Runtime exception response
 */
export interface RuntimeExceptionResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 响应数据 */
  data?: unknown;
  /** 数据总数量 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * 产品类型
 */
export type UpdateProductRequestType = typeof UpdateProductRequestType[keyof typeof UpdateProductRequestType];


export const UpdateProductRequestType = {
  NEWSPAPER: 'NEWSPAPER',
  MAGAZINE: 'MAGAZINE',
} as const;

/**
 * Update product request
 */
export interface UpdateProductRequest {
  /**
   * 产品名称
   * @minLength 1
   * @maxLength 100
   */
  name?: string;
  /** 产品类型 */
  type?: UpdateProductRequestType;
  /**
   * 销售价格
   * @minimum 0.01
   * @maximum 999999.99
   */
  price?: number;
}

/**
 * 产品类型
 */
export type ProductVOType = typeof ProductVOType[keyof typeof ProductVOType];


export const ProductVOType = {
  NEWSPAPER: 'NEWSPAPER',
  MAGAZINE: 'MAGAZINE',
} as const;

/**
 * Product view object
 */
export interface ProductVO {
  /** 产品ID */
  id?: string;
  /** 产品名称 */
  name?: string;
  /** 产品类型 */
  type?: ProductVOType;
  /** 销售价格 */
  price?: number;
  /** 当前库存数量 */
  stock?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新时间 */
  updatedAt?: string;
}

/**
 * Create product responses
 */
export interface ProductVOResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 产品数据 */
  data?: ProductVO;
  /** 数据总数量 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * Resource does not exist response
 */
export interface NotFoundExceptionResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 响应数据 */
  data?: unknown;
  /** 数据总数量 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * Sale item request (single product in the order)
 */
export interface SaleItemRequest {
  /**
   * 产品ID (UUIDv7)
   * @minLength 1
   */
  productId: string;
  /**
   * 购买数量
   * @minimum 1
   * @maximum 9999
   */
  quantity: number;
}

/**
 * Create sale order request
 */
export interface CreateSaleRequest {
  /**
   * 购物车商品列表（至少1个商品）
   * @minItems 1
   */
  items: SaleItemRequest[];
}

/**
 * Sale item view object
 */
export interface SaleItemVO {
  /** 明细ID */
  id?: string;
  /** 关联产品ID */
  productId?: string;
  /** 产品名称（销售时快照） */
  productName?: string;
  /** 单价（销售时快照） */
  unitPrice?: number;
  /** 购买数量 */
  quantity?: number;
  /** 小计金额（单价 × 数量） */
  subtotal?: number;
}

/**
 * Sale order view object (includes item details)
 */
export interface SaleOrderVO {
  /** 订单ID */
  id?: string;
  /** 订单号 */
  orderNumber?: string;
  /** 订单总金额 */
  totalAmount?: number;
  /** 商品种类数量 */
  itemCount?: number;
  /** 商品总数量 */
  totalQuantity?: number;
  /** 订单创建时间 */
  createdAt?: string;
  /** 订单明细列表 */
  items?: SaleItemVO[];
}

/**
 * Create sale order response
 */
export interface SaleOrderVOResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 销售订单数据（含明细列表） */
  data?: SaleOrderVO;
  /** 数据总数量 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * 产品类型
 */
export type CreateProductRequestType = typeof CreateProductRequestType[keyof typeof CreateProductRequestType];


export const CreateProductRequestType = {
  NEWSPAPER: 'NEWSPAPER',
  MAGAZINE: 'MAGAZINE',
} as const;

/**
 * Create product request
 */
export interface CreateProductRequest {
  /**
   * 产品名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 产品类型 */
  type: CreateProductRequestType;
  /**
   * 销售价格
   * @minimum 0.01
   * @maximum 999999.99
   */
  price: number;
  /**
   * 初始库存数量
   * @minimum 0
   */
  stock: number;
}

/**
 * Adjust product stock request
 */
export interface AdjustStockRequest {
  /**
   * 库存调整量（正数为增加，负数为减少）
   * @minimum -9999
   * @maximum 9999
   */
  quantity: number;
}

/**
 * Business logic error response
 */
export interface BusinessExceptionResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 响应数据 */
  data?: unknown;
  /** 数据总数量 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * Query sale history request
 */
export interface QuerySaleHistoryRequest {
  /**
   * 页码（从0开始，0表示第一页）
   * @minimum 0
   */
  page?: number;
  /**
   * 每页数量（1-100之间）
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  /** 开始日期（格式：yyyy-MM-dd，可选） */
  startDate?: string;
  /** 结束日期（格式：yyyy-MM-dd，可选） */
  endDate?: string;
}

/**
 * Sale history list response
 */
export interface SaleOrderListResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 销售订单列表（不含明细） */
  data?: SaleOrderVO[];
  /** 总记录数 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * Sales breakdown by product category
 */
export interface CategorySalesVO {
  /** 报纸销售额（当日无记录时为0） */
  newspaperAmount?: number;
  /** 杂志销售额（当日无记录时为0） */
  magazineAmount?: number;
  /** 报纸销售占比（百分比，0-100，当日无记录时为0） */
  newspaperPercentage?: number;
  /** 杂志销售占比（百分比，0-100，当日无记录时为0） */
  magazinePercentage?: number;
}

/**
 * Top selling product info
 */
export interface TopProductVO {
  /** 商品名称 */
  productName?: string;
  /** 销售数量 */
  totalQuantity?: number;
}

/**
 * Daily sales report data
 */
export interface DailyReportVO {
  /** 查询日期 */
  date?: string;
  /** 总销售额（当日无记录时为0） */
  totalAmount?: number;
  /** 订单总数（当日无记录时为0） */
  orderCount?: number;
  /** TOP5畅销商品列表（当日无记录时为空列表） */
  topProducts?: TopProductVO[];
  /** 各类别销售统计（当日无记录时金额为0、占比为0） */
  categorySales?: CategorySalesVO;
}

/**
 * Daily sales report response
 */
export interface DailyReportVOResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 日报统计数据 */
  data?: DailyReportVO;
  /** 数据总数量 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * 产品类型（可选，不传则查询全部）
 */
export type QueryProductRequestType = typeof QueryProductRequestType[keyof typeof QueryProductRequestType];


export const QueryProductRequestType = {
  NEWSPAPER: 'NEWSPAPER',
  MAGAZINE: 'MAGAZINE',
} as const;

/**
 * Query product list request
 */
export interface QueryProductRequest {
  /**
   * 页码（从0开始，0表示第一页）
   * @minimum 0
   */
  page?: number;
  /**
   * 每页数量（1-100之间）
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  /** 产品类型（可选，不传则查询全部） */
  type?: QueryProductRequestType;
}

/**
 * Query product response by page
 */
export interface ProductListResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 产品列表 */
  data?: ProductVO[];
  /** 总记录数 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * Stock check result
 */
export interface StockCheckVO {
  /** 库存是否充足（true=充足，false=不足） */
  available?: boolean;
  /** 当前库存数量 */
  currentStock?: number;
}

/**
 * Stock check response
 */
export interface StockCheckResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 库存验证结果 */
  data?: StockCheckVO;
  /** 数据总数量 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * Query low stock products request
 */
export interface QueryLowStockRequest {
  /**
   * 页码（从0开始，0表示第一页）
   * @minimum 0
   */
  page?: number;
  /**
   * 每页数量（1-100之间）
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  /**
   * 库存阈值（可选，默认10，返回库存<=此值的产品）
   * @minimum 0
   */
  threshold?: number;
}

/**
 * Low stock products response
 */
export interface LowStockProductListResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 低库存产品列表 */
  data?: ProductVO[];
  /** 总记录数 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * Delete product response
 */
export interface VoidResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  data?: unknown;
  /** 数据总数量 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

export type GetSaleHistoryParams = {
request: QuerySaleHistoryRequest;
/**
 * **Page number (starts from 0, 0 means first page)**
 * @minimum 0
 */
page?: number;
/**
 * Page size (1-100)
 * @minimum 1
 * @maximum 100
 */
size?: number;
/**
 * Start date (inclusive, format: yyyy-MM-dd, optional)
 */
startDate?: string;
/**
 * End date (inclusive, format: yyyy-MM-dd, optional)
 */
endDate?: string;
};

export type QueryProductsParams = {
request: QueryProductRequest;
/**
 * **Page number (starts from 0, 0 means first page)**
 * @minimum 0
 */
page?: number;
/**
 * Page size (1-100)
 * @minimum 1
 * @maximum 100
 */
size?: number;
/**
 * Product type (optional, query all if not specified)
 */
type?: QueryProductsType;
};

export type QueryProductsType = typeof QueryProductsType[keyof typeof QueryProductsType];


export const QueryProductsType = {
  NEWSPAPER: 'NEWSPAPER',
  MAGAZINE: 'MAGAZINE',
} as const;

export type GetDailyReportParams = {
/**
 * Query date (format: yyyy-MM-dd, defaults to today if not provided)
 */
date?: string;
};

export type CheckStockParams = {
/**
 * Required quantity to check (must be greater than 0)
 * @minimum 1
 */
quantity: number;
};

export type GetLowStockProductsParams = {
request: QueryLowStockRequest;
/**
 * **Page number (starts from 0, 0 means first page)**
 * @minimum 0
 */
page?: number;
/**
 * Page size (1-100)
 * @minimum 1
 * @maximum 100
 */
size?: number;
/**
 * Stock threshold (optional, default 10, returns products with stock <= this value)
 * @minimum 0
 */
threshold?: number;
};

