/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Newsstand Management System API
 * Newsstand Management System RESTful API Documentation
 * OpenAPI spec version: v1.0.0
 */
/**
 * Resource conflict response
 */
export interface ConflictExceptionResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 响应数据 */
  data?: unknown;
  /** 数据总数量 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * Parameter validation failure response
 */
export interface ValidationExceptionResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 字段错误信息，格式：field1: message1; field2: message2 */
  errorMsg?: string;
  /** 响应数据 */
  data?: unknown;
  /** 数据总数量 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * Runtime exception response
 */
export interface RuntimeExceptionResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 响应数据 */
  data?: unknown;
  /** 数据总数量 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * 产品类型
 */
export type UpdateProductRequestType = typeof UpdateProductRequestType[keyof typeof UpdateProductRequestType];


export const UpdateProductRequestType = {
  NEWSPAPER: 'NEWSPAPER',
  MAGAZINE: 'MAGAZINE',
} as const;

/**
 * Update product request
 */
export interface UpdateProductRequest {
  /**
   * 产品名称
   * @minLength 1
   * @maxLength 100
   */
  name?: string;
  /** 产品类型 */
  type?: UpdateProductRequestType;
  /**
   * 销售价格
   * @minimum 0.01
   * @maximum 999999.99
   */
  price?: number;
}

/**
 * 产品类型
 */
export type ProductVOType = typeof ProductVOType[keyof typeof ProductVOType];


export const ProductVOType = {
  NEWSPAPER: 'NEWSPAPER',
  MAGAZINE: 'MAGAZINE',
} as const;

/**
 * Product view object
 */
export interface ProductVO {
  /** 产品ID */
  id?: string;
  /** 产品名称 */
  name?: string;
  /** 产品类型 */
  type?: ProductVOType;
  /** 销售价格 */
  price?: number;
  /** 当前库存数量 */
  stock?: number;
  /** 创建时间 */
  createdAt?: string;
  /** 更新时间 */
  updatedAt?: string;
}

/**
 * Create product responses
 */
export interface ProductVOResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 产品数据 */
  data?: ProductVO;
  /** 数据总数量 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * Resource does not exist response
 */
export interface NotFoundExceptionResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 响应数据 */
  data?: unknown;
  /** 数据总数量 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * 产品类型
 */
export type CreateProductRequestType = typeof CreateProductRequestType[keyof typeof CreateProductRequestType];


export const CreateProductRequestType = {
  NEWSPAPER: 'NEWSPAPER',
  MAGAZINE: 'MAGAZINE',
} as const;

/**
 * Create product request
 */
export interface CreateProductRequest {
  /**
   * 产品名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 产品类型 */
  type: CreateProductRequestType;
  /**
   * 销售价格
   * @minimum 0.01
   * @maximum 999999.99
   */
  price: number;
  /**
   * 初始库存数量
   * @minimum 0
   */
  stock: number;
}

/**
 * Adjust product stock request
 */
export interface AdjustStockRequest {
  /**
   * 库存调整量（正数为增加，负数为减少）
   * @minimum -9999
   * @maximum 9999
   */
  quantity: number;
}

/**
 * Business logic error response
 */
export interface BusinessExceptionResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 响应数据 */
  data?: unknown;
  /** 数据总数量 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

/**
 * 产品类型（可选，不传则查询全部）
 */
export type QueryProductRequestType = typeof QueryProductRequestType[keyof typeof QueryProductRequestType];


export const QueryProductRequestType = {
  NEWSPAPER: 'NEWSPAPER',
  MAGAZINE: 'MAGAZINE',
} as const;

/**
 * Query product list request
 */
export interface QueryProductRequest {
  /**
   * 页码（从0开始，0表示第一页）
   * @minimum 0
   */
  page?: number;
  /**
   * 每页数量（1-100之间）
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  /** 产品类型（可选，不传则查询全部） */
  type?: QueryProductRequestType;
}

/**
 * Query product response by page
 */
export interface ProductListResult {
  /** 操作是否成功 */
  success?: boolean;
  /** 错误信息 */
  errorMsg?: string;
  /** 产品列表 */
  data?: ProductVO[];
  /** 总记录数 */
  total?: number;
  /** 总页数 */
  totalPages?: number;
}

export type QueryProductsParams = {
request: QueryProductRequest;
/**
 * **Page number (starts from 0, 0 means first page)**
 * @minimum 0
 */
page?: number;
/**
 * Page size (1-100)
 * @minimum 1
 * @maximum 100
 */
size?: number;
/**
 * Product type (optional, query all if not specified)
 */
type?: QueryProductsType;
};

export type QueryProductsType = typeof QueryProductsType[keyof typeof QueryProductsType];


export const QueryProductsType = {
  NEWSPAPER: 'NEWSPAPER',
  MAGAZINE: 'MAGAZINE',
} as const;

