/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Newsstand Management System API
 * Newsstand Management System RESTful API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';

import { request } from '../request';
import type {
  ConflictExceptionResult,
  CreateProductRequest,
  NotFoundExceptionResult,
  ProductListResult,
  ProductVOResult,
  QueryProductsParams,
  RuntimeExceptionResult,
  UpdateProductRequest,
  ValidationExceptionResult
} from './newsstandManagementSystemAPI.schemas';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Update product name, type and price. Stock adjustment is handled by a separate endpoint.
 * @summary Update product
 */
export const getUpdateProductUrl = (id: string,) => {


  

  return `/api/products/${id}`
}

export const updateProduct = async (id: string,
    updateProductRequest: UpdateProductRequest, options?: RequestInit): Promise<ProductVOResult> => {
  
  return request<ProductVOResult>(getUpdateProductUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProductRequest,)
  }
);}




export const getUpdateProductMutationOptions = <TError = ValidationExceptionResult | NotFoundExceptionResult | RuntimeExceptionResult,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: string;data: UpdateProductRequest}, TContext>, request?: SecondParameter<typeof request>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: string;data: UpdateProductRequest}, TContext> => {

const mutationKey = ['updateProduct'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProduct>>, {id: string;data: UpdateProductRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateProduct(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProductMutationResult = NonNullable<Awaited<ReturnType<typeof updateProduct>>>
    export type UpdateProductMutationBody = UpdateProductRequest
    export type UpdateProductMutationError = ValidationExceptionResult | NotFoundExceptionResult | RuntimeExceptionResult

    /**
 * @summary Update product
 */
export const useUpdateProduct = <TError = ValidationExceptionResult | NotFoundExceptionResult | RuntimeExceptionResult,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: string;data: UpdateProductRequest}, TContext>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProduct>>,
        TError,
        {id: string;data: UpdateProductRequest},
        TContext
      > => {
      return useMutation(getUpdateProductMutationOptions(options), queryClient);
    }
    /**
 * Query product list with pagination and optional type filter. Returns non-deleted products ordered by creation time descending. **IMPORTANT: page parameter starts from 0 (0 = first page)**
 * @summary Query product list with pagination
 */
export const getQueryProductsUrl = (params: QueryProductsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/products?${stringifiedParams}` : `/api/products`
}

export const queryProducts = async (params: QueryProductsParams, options?: RequestInit): Promise<ProductListResult> => {
  
  return request<ProductListResult>(getQueryProductsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getQueryProductsQueryKey = (params?: QueryProductsParams,) => {
    return [
    `/api/products`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getQueryProductsQueryOptions = <TData = Awaited<ReturnType<typeof queryProducts>>, TError = ValidationExceptionResult | RuntimeExceptionResult>(params: QueryProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof queryProducts>>, TError, TData>>, request?: SecondParameter<typeof request>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getQueryProductsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof queryProducts>>> = ({ signal }) => queryProducts(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof queryProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type QueryProductsQueryResult = NonNullable<Awaited<ReturnType<typeof queryProducts>>>
export type QueryProductsQueryError = ValidationExceptionResult | RuntimeExceptionResult


export function useQueryProducts<TData = Awaited<ReturnType<typeof queryProducts>>, TError = ValidationExceptionResult | RuntimeExceptionResult>(
 params: QueryProductsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof queryProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryProducts>>,
          TError,
          Awaited<ReturnType<typeof queryProducts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useQueryProducts<TData = Awaited<ReturnType<typeof queryProducts>>, TError = ValidationExceptionResult | RuntimeExceptionResult>(
 params: QueryProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof queryProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryProducts>>,
          TError,
          Awaited<ReturnType<typeof queryProducts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useQueryProducts<TData = Awaited<ReturnType<typeof queryProducts>>, TError = ValidationExceptionResult | RuntimeExceptionResult>(
 params: QueryProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof queryProducts>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Query product list with pagination
 */

export function useQueryProducts<TData = Awaited<ReturnType<typeof queryProducts>>, TError = ValidationExceptionResult | RuntimeExceptionResult>(
 params: QueryProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof queryProducts>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getQueryProductsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a new newspaper or magazine product, the product name cannot be repeated
 * @summary Create product
 */
export const getCreateProductUrl = () => {


  

  return `/api/products`
}

export const createProduct = async (createProductRequest: CreateProductRequest, options?: RequestInit): Promise<ProductVOResult> => {
  
  return request<ProductVOResult>(getCreateProductUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProductRequest,)
  }
);}




export const getCreateProductMutationOptions = <TError = ValidationExceptionResult | ConflictExceptionResult | RuntimeExceptionResult,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: CreateProductRequest}, TContext>, request?: SecondParameter<typeof request>}
): UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: CreateProductRequest}, TContext> => {

const mutationKey = ['createProduct'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProduct>>, {data: CreateProductRequest}> = (props) => {
          const {data} = props ?? {};

          return  createProduct(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProductMutationResult = NonNullable<Awaited<ReturnType<typeof createProduct>>>
    export type CreateProductMutationBody = CreateProductRequest
    export type CreateProductMutationError = ValidationExceptionResult | ConflictExceptionResult | RuntimeExceptionResult

    /**
 * @summary Create product
 */
export const useCreateProduct = <TError = ValidationExceptionResult | ConflictExceptionResult | RuntimeExceptionResult,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: CreateProductRequest}, TContext>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProduct>>,
        TError,
        {data: CreateProductRequest},
        TContext
      > => {
      return useMutation(getCreateProductMutationOptions(options), queryClient);
    }
    