/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Newsstand Management System API
 * Newsstand Management System RESTful API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';
import {
  useQuery
} from '@tanstack/react-query';

import { request } from '../request';
import type {
  DailyReportVOResult,
  GetDailyReportParams,
  RuntimeExceptionResult,
  ValidationExceptionResult
} from './newsstandManagementSystemAPI.schemas';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get sales statistics for a specific date, including total amount, order count, top 5 best-selling products, and sales breakdown by category (NEWSPAPER/MAGAZINE). If no sales records exist for the date, returns an empty data structure (amounts as 0, lists empty) rather than 404. Defaults to today if date parameter is not provided.
 * @summary Get daily sales report
 */
export const getGetDailyReportUrl = (params?: GetDailyReportParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/reports/daily?${stringifiedParams}` : `/api/reports/daily`
}

export const getDailyReport = async (params?: GetDailyReportParams, options?: RequestInit): Promise<DailyReportVOResult> => {
  
  return request<DailyReportVOResult>(getGetDailyReportUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetDailyReportQueryKey = (params?: GetDailyReportParams,) => {
    return [
    `/api/reports/daily`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetDailyReportQueryOptions = <TData = Awaited<ReturnType<typeof getDailyReport>>, TError = ValidationExceptionResult | RuntimeExceptionResult>(params?: GetDailyReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailyReport>>, TError, TData>>, request?: SecondParameter<typeof request>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDailyReportQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDailyReport>>> = ({ signal }) => getDailyReport(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDailyReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDailyReportQueryResult = NonNullable<Awaited<ReturnType<typeof getDailyReport>>>
export type GetDailyReportQueryError = ValidationExceptionResult | RuntimeExceptionResult


export function useGetDailyReport<TData = Awaited<ReturnType<typeof getDailyReport>>, TError = ValidationExceptionResult | RuntimeExceptionResult>(
 params: undefined |  GetDailyReportParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailyReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDailyReport>>,
          TError,
          Awaited<ReturnType<typeof getDailyReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDailyReport<TData = Awaited<ReturnType<typeof getDailyReport>>, TError = ValidationExceptionResult | RuntimeExceptionResult>(
 params?: GetDailyReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailyReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDailyReport>>,
          TError,
          Awaited<ReturnType<typeof getDailyReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDailyReport<TData = Awaited<ReturnType<typeof getDailyReport>>, TError = ValidationExceptionResult | RuntimeExceptionResult>(
 params?: GetDailyReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailyReport>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get daily sales report
 */

export function useGetDailyReport<TData = Awaited<ReturnType<typeof getDailyReport>>, TError = ValidationExceptionResult | RuntimeExceptionResult>(
 params?: GetDailyReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailyReport>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDailyReportQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




