/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Newsstand Management System API
 * Newsstand Management System RESTful API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';

import { request } from '../request';
import type {
  CreateSaleRequest,
  GetSaleHistoryParams,
  NotFoundExceptionResult,
  RuntimeExceptionResult,
  SaleOrderListResult,
  SaleOrderVOResult,
  ValidationExceptionResult
} from './newsstandManagementSystemAPI.schemas';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Query sale order history with pagination and optional date range filter. Returns orders sorted by creation time descending. Items (line details) are NOT included in list results; use GET /api/sales/{id} to get details. **IMPORTANT: page parameter starts from 0 (0 = first page)**
 * @summary Query sale history with pagination
 */
export const getGetSaleHistoryUrl = (params: GetSaleHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/sales?${stringifiedParams}` : `/api/sales`
}

export const getSaleHistory = async (params: GetSaleHistoryParams, options?: RequestInit): Promise<SaleOrderListResult> => {
  
  return request<SaleOrderListResult>(getGetSaleHistoryUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetSaleHistoryQueryKey = (params?: GetSaleHistoryParams,) => {
    return [
    `/api/sales`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetSaleHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getSaleHistory>>, TError = ValidationExceptionResult | RuntimeExceptionResult>(params: GetSaleHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaleHistory>>, TError, TData>>, request?: SecondParameter<typeof request>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSaleHistoryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSaleHistory>>> = ({ signal }) => getSaleHistory(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSaleHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSaleHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getSaleHistory>>>
export type GetSaleHistoryQueryError = ValidationExceptionResult | RuntimeExceptionResult


export function useGetSaleHistory<TData = Awaited<ReturnType<typeof getSaleHistory>>, TError = ValidationExceptionResult | RuntimeExceptionResult>(
 params: GetSaleHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaleHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSaleHistory>>,
          TError,
          Awaited<ReturnType<typeof getSaleHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSaleHistory<TData = Awaited<ReturnType<typeof getSaleHistory>>, TError = ValidationExceptionResult | RuntimeExceptionResult>(
 params: GetSaleHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaleHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSaleHistory>>,
          TError,
          Awaited<ReturnType<typeof getSaleHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSaleHistory<TData = Awaited<ReturnType<typeof getSaleHistory>>, TError = ValidationExceptionResult | RuntimeExceptionResult>(
 params: GetSaleHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaleHistory>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Query sale history with pagination
 */

export function useGetSaleHistory<TData = Awaited<ReturnType<typeof getSaleHistory>>, TError = ValidationExceptionResult | RuntimeExceptionResult>(
 params: GetSaleHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaleHistory>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSaleHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Complete a sale transaction: validates stock, deducts inventory, creates the order and its items. Returns the full order with item details. Uses optimistic locking to prevent concurrent stock issues.
 * @summary Create sale order
 */
export const getCreateSaleUrl = () => {


  

  return `/api/sales`
}

export const createSale = async (createSaleRequest: CreateSaleRequest, options?: RequestInit): Promise<SaleOrderVOResult> => {
  
  return request<SaleOrderVOResult>(getCreateSaleUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSaleRequest,)
  }
);}




export const getCreateSaleMutationOptions = <TError = ValidationExceptionResult | NotFoundExceptionResult | RuntimeExceptionResult,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSale>>, TError,{data: CreateSaleRequest}, TContext>, request?: SecondParameter<typeof request>}
): UseMutationOptions<Awaited<ReturnType<typeof createSale>>, TError,{data: CreateSaleRequest}, TContext> => {

const mutationKey = ['createSale'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSale>>, {data: CreateSaleRequest}> = (props) => {
          const {data} = props ?? {};

          return  createSale(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateSaleMutationResult = NonNullable<Awaited<ReturnType<typeof createSale>>>
    export type CreateSaleMutationBody = CreateSaleRequest
    export type CreateSaleMutationError = ValidationExceptionResult | NotFoundExceptionResult | RuntimeExceptionResult

    /**
 * @summary Create sale order
 */
export const useCreateSale = <TError = ValidationExceptionResult | NotFoundExceptionResult | RuntimeExceptionResult,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSale>>, TError,{data: CreateSaleRequest}, TContext>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSale>>,
        TError,
        {data: CreateSaleRequest},
        TContext
      > => {
      return useMutation(getCreateSaleMutationOptions(options), queryClient);
    }
    /**
 * Get complete sale order details (including all items) by order ID. Returns 404 if the order does not exist.
 * @summary Get sale order by ID
 */
export const getGetSaleByIdUrl = (id: string,) => {


  

  return `/api/sales/${id}`
}

export const getSaleById = async (id: string, options?: RequestInit): Promise<SaleOrderVOResult> => {
  
  return request<SaleOrderVOResult>(getGetSaleByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetSaleByIdQueryKey = (id: string,) => {
    return [
    `/api/sales/${id}`
    ] as const;
    }

    
export const getGetSaleByIdQueryOptions = <TData = Awaited<ReturnType<typeof getSaleById>>, TError = NotFoundExceptionResult | RuntimeExceptionResult>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaleById>>, TError, TData>>, request?: SecondParameter<typeof request>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSaleByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSaleById>>> = ({ signal }) => getSaleById(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSaleById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSaleByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getSaleById>>>
export type GetSaleByIdQueryError = NotFoundExceptionResult | RuntimeExceptionResult


export function useGetSaleById<TData = Awaited<ReturnType<typeof getSaleById>>, TError = NotFoundExceptionResult | RuntimeExceptionResult>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaleById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSaleById>>,
          TError,
          Awaited<ReturnType<typeof getSaleById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSaleById<TData = Awaited<ReturnType<typeof getSaleById>>, TError = NotFoundExceptionResult | RuntimeExceptionResult>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaleById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSaleById>>,
          TError,
          Awaited<ReturnType<typeof getSaleById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSaleById<TData = Awaited<ReturnType<typeof getSaleById>>, TError = NotFoundExceptionResult | RuntimeExceptionResult>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaleById>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get sale order by ID
 */

export function useGetSaleById<TData = Awaited<ReturnType<typeof getSaleById>>, TError = NotFoundExceptionResult | RuntimeExceptionResult>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaleById>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSaleByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




